### Register
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "email": "test@sentinel.com",
  "password": "password123"
}

### Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "test@sentinel.com",
  "password": "password123"
}

### Get API Key
POST http://localhost:8080/api/keys
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0QHNlbnRpbmVsLmNvbSIsImlhdCI6MTc3Mjk1MDg2MywiZXhwIjoxNzcyOTU0NDYzfQ.wFPp1rZnlxeyptwHPaq9QwgF_5zeDjb6O2qlfpL-KjHk_8xuQcyUlV8OZL-a480z-YSI07J5FRhZ1h3Z9BremA

### Test API Key
POST http://localhost:8080/api/keys
X-API-KEY: 5c16ea4b63874adf8ac07740ae241cd2


### Test Actuactor paths
GET http://localhost:8080/actuator/health
X-API-KEY: 5c16ea4b63874adf8ac07740ae241cd2

### Hit /api/dummy endpoint
GET http://localhost:8080/api/dummy
X-API-KEY: 5c16ea4b63874adf8ac07740ae241cd2