### Register
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "email": "test@sentinel.com",
  "password": "password123"
}

### Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "test@sentinel.com",
  "password": "password123"
}

### Get API Key
POST http://localhost:8080/api/keys
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0QHNlbnRpbmVsLmNvbSIsImlhdCI6MTc3MTk0Nzk0MiwiZXhwIjoxNzcxOTUxNTQyfQ.mty30jyZzPpWLm4yPJkBdIzsdrmN8ZKbMSpmIrEZTZN24jVXOqTLRxFfWUUwHlAAr-gOTjaY5ndyabtCX8TIUw

### Test API Key
POST http://localhost:8080/api/keys
X-API-KEY: 5c16ea4b63874adf8ac07740ae241cd2


### Test Actuactor paths
GET http://localhost:8080/actuator/health
X-API-KEY: 5c16ea4b63874adf8ac07740ae241cd2
